pipeline:
  name: simple pipeline
  identifier: simple_pipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.account_level_github_connector
        repoName: harness_mission_4
        build: <+input>
  stages:
    - stage:
        name: Run Script
        identifier: Run_Script
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.safina_build_farm_connector
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run Script
                  identifier: Run_Script
                  spec:
                    connectorRef: account.account_level_docker_connector
                    image: bash
                    shell: Sh
                    command: sh run.sh
